[changelog]
header = """
## ğŸ“… Changes
"""
body = """
{% if version %}\
    {% if previous.version %}\
        ### [{{ version | trim_start_matches(pat="v") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/compare/{{ previous.version }}...{{ version }})
    {% else %}\
        ### {{ version | trim_start_matches(pat="v") }}
    {% endif %}\
{% else %}\
    ### [unreleased]
{% endif %}\

{% for group, commits in commits | group_by(attribute="group") %}
    #### {{ group | upper_first }}
    {% for commit in commits %}
        - {{ commit.message | upper_first }} ([{{ commit.id | truncate(length=7, end="") }}](https://github.com/{{ remote.github.owner }}/{{ remote.github.repo }}/commit/{{ commit.id }}))\
          {% if commit.github.username %} by @{{ commit.github.username }}{%- endif -%}
    {% endfor %}
{% endfor %}
"""
trim = true
footer = """
"""

[git]
conventional_commits = true
filter_unconventional = false
split_commits = false
commit_parsers = [
    { message = "(?i)^feat", group = "ğŸš€ Features" },
    { message = "(?i)^fix", group = "ğŸ› Bug Fixes" },
    { message = "(?i)^doc", group = "ğŸ“š Documentation" },
    { message = "(?i)^perf", group = "âš¡ Performance" },
    { message = "(?i)^refactor", group = "ğŸ›  Refactor" },
    { message = "(?i)^style", group = "ğŸ¨ Styling" },
    { message = "(?i)^test", group = "ğŸ§ª Testing" },
    { message = "^chore\\(release\\): prepare for", skip = true },
    { message = "(?i)^chore", group = "âš™ï¸ Miscellaneous" },
    { body = ".*security", group = "ğŸ›¡ï¸ Security" },
]
protect_breaking_commits = false
filter_commits = false
tag_pattern = "v?[0-9].*"
skip_tags = "beta|alpha"


ignore_tags = ""
sort_commits = "oldest"
